name: plyvel build

on:
  # Triggers the workflow on push to the main branch
  push:
    tags:
      - "v*"
    # branches: [CI]
  # pull_request:
  #   branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  wheel:
    name: Build ${{ matrix.name }} wheels
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write # This line fixes the softprops action error
    strategy:
      matrix:
        include:
          - os: macos-15
            name: macos-15
            cibw:
              platform: macos
              arch: universal2
              build: "cp311-* cp312-* cp314-*"
              version: 15.0
          - os: macos-26
            name: macos-26
            cibw:
              platform: macos
              arch: universal2
              build: "cp311-* cp312-* cp314-*"
              version: 26.0
          - os: ubuntu-24.04
            name: linux
            cibw:
              platform: linux
              # auto = x86_64, usually WSL2 users
              arch: auto aarch64
              build: "cp311-* cp312-* cp314-*"
              version: 24.04
    env:
      CIBW_BUILD: "${{ matrix.cibw.build || '*' }}"
      CIBW_PLATFORM: "${{ matrix.cibw.platform || '' }}"
      # `CPLUS_INCLUDE_PATH` and `LIBRARY_PATH` for `setup.py` to link leveldb and snappy headers and libs in macOS
      CIBW_ENVIRONMENT_MACOS: >
        C_INCLUDE_PATH="/usr/local/include:$C_INCLUDE_PATH"
        CPLUS_INCLUDE_PATH="/usr/local/include:$CPLUS_INCLUDE_PATH"
        LIBRARY_PATH="/usr/local/lib:$LIBRARY_PATH"
      CIBW_BEFORE_ALL_LINUX: "gcc -v && bash scripts/install-snappy.sh && bash scripts/install-leveldb.sh"
      CIBW_BEFORE_ALL_MACOS: "clang -v && bash scripts/install-snappy.sh && bash scripts/install-leveldb.sh"
      CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel repair --lib-sdir . -w {dest_dir} {wheel}"
      CIBW_REPAIR_WHEEL_COMMAND_MACOS: "delocate-listdeps {wheel} && delocate-wheel -w {dest_dir} {wheel} -v"
      CIBW_TEST_REQUIRES: "pytest"
      CIBW_TEST_COMMAND: "pytest -v {package}/test"
      MACOSX_DEPLOYMENT_TARGET: "${{ matrix.cibw.version }}"
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python 3.11
        if: matrix.cibw.build == 'cp311*-'
        uses: actions/setup-python@v7
        with:
          python-version: 3.11
          cache: pip # caching pip dependencies

      - name: Set up Python 3.12
        if: matrix.cibw.build == 'cp312-*'
        uses: actions/setup-python@v7
        with:
          python-version: 3.12
          cache: pip # caching pip dependencies

      - name: Set up Python 3.14
        if: matrix.cibw.build == 'cp314-*'
        uses: actions/setup-python@v7
        with:
          python-version: 3.14
          cache: pip # caching pip dependencies

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v4
        with:
          platforms: all

      - name: Install cibuildwheel
        run: |
          pip install -U setuptools pip wheel
          pip install -U cibuildwheel

      - name: Run cibuildwheel
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: "${{ matrix.name }}"
          path: ./wheelhouse/*.whl

  merge:
    runs-on: ubuntu-latest
    needs: wheel
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          delete-merged: true

  release:
    name: Release to github
    # when we make a new "release" in GitHub, we don't need the sdist to be made again
    needs: merge
    runs-on: ubuntu-latest
    permissions:
      contents: write # This line fixes the softprops action error
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: merged-artifacts
          path: wheelhouse
      - uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: wheelhouse/*
